@base_url = http://localhost:3000
@content_type = application/json

### Get all users
GET {{base_url}}/user

### Get user by id
GET {{base_url}}/user/dc62da74-18f0-4e20-9987-fac364032c28

### Create user
POST {{base_url}}/user
content-type: {{content_type}}

{
    "firstName": "Andre",
    "lastName": "Alves",
    "email": "email@email.com",
    "password": "1234",
    "localityId": "1"
}

### Get all countries
GET {{base_url}}/country

### Create country
POST {{base_url}}/country
content-type: {{content_type}}

{
    "name": "Brazil"
}

### Get all localities
GET {{base_url}}/locality

### Create locality
POST {{base_url}}/locality
content-type: {{content_type}}

{
    "name": "Sao Paulo",
    "countryId": "9b11eea6-6871-4762-9171-a66a9bd8203b"
}

### Get all brands
GET {{base_url}}/brand

### Get all models
GET {{base_url}}/model

### Get all vote types
GET {{base_url}}/vote-type

### Get all fuels
GET {{base_url}}/fuel

### Get all versions
GET {{base_url}}/version

### Get all opinions
GET {{base_url}}/opinion

### Get opinion by id
GET {{base_url}}/opinion/1

### Get all vehicles
GET {{base_url}}/vehicle